steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/first-laravel-project:$COMMIT_SHA"
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/first-laravel-project:$COMMIT_SHA"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "first-laravel-project"
      - "--image=gcr.io/$PROJECT_ID/first-laravel-project:$COMMIT_SHA"
      - "--region=asia-southeast2"
      - "--cpu=2"
      - "--memory=2048Mi"
      - "--allow-unauthenticated"
      - "--set-secrets=DB_HOST=db-host:latest,DB_USERNAME=db-username:latest,DB_PASSWORD=db-password:latest,DB_DATABASE=db-database:latest,APP-KEY=app-key:latest"
images:
  - "gcr.io/$PROJECT_ID/first-laravel-project:$COMMIT_SHA"
logsBucket: "gs://laravel-buckets/logs"
